---
# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

on: # yamllint disable-line rule:truthy
  pull_request:
  merge_group:

name: üè∑Ô∏è Add labels

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: üè∑Ô∏è Apply labels
        uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
